[mypy]
python_version = 3.11
ignore_missing_imports = True
disable_error_code = attr-defined,no-redef,assignment,misc

[mypy.ohm.bayesian]
ignore_errors = True

[mypy.ohm.sdk]
ignore_errors = True

[mypy.ohm.framework.*]
ignore_errors = True