[mypy]
python_version = 3.13
ignore_missing_imports = True
disable_error_code = attr-defined,no-redef,assignment,misc,name-defined,arg-type,index,override,union-attr,return-value,var-annotated,dict-item,operator,call-arg,call-overload

[mypy.ohm.bayesian]
ignore_errors = True

[mypy.ohm.sdk]
ignore_errors = True

[mypy.ohm.framework.*]
ignore_errors = True

[mypy.ohm.inference.*]
ignore_errors = True

[mypy.ohm.patterns]
ignore_errors = True

[mypy.ohm.tenant]
ignore_errors = True
